version: '3.9'

services:

  db:
    image: postgres:15
    container_name: flexi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sumapln
      POSTGRES_DB: flexiserve_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flexi-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:sumapln@db/flexiserve_db

  frontend:
    build:
      context: ../frontend
    container_name: flexi-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
