name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sumapln
          POSTGRES_DB: flexiserve_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Alembic migrations
        run: |
          cd backend
          alembic upgrade head

      - name: Start FastAPI with Uvicorn (in background)
        run: |
          cd backend
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10  # wait for the server to start

      - name: Test FastAPI health endpoint
        run: |
          curl http://localhost:8000/

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
