name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sumapln
          POSTGRES_DB: flexiserve_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (backend)
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Alembic migration
        run: |
          cd backend
          alembic upgrade head

      - name: Test FastAPI health endpoint (backend must already be running)
        run: curl http://localhost:8000/

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
